remote_theme: https://github.com/just-the-docs/just-the-docs                                                                                                                                             
# remote_theme: rundocs/jekyll-rtd-theme                                                                                                                                                                 
plugins:                                                                                                                                                                                                 
- jekyll-remote-theme # add this line to the plugins list if you already have one                                                                                                                        
title: QBS Documentation
description: Official user documentation for QBS — Accounting, Finance, and more.
footer_content: "Copyright &copy; 2026 QAL ERP. All rights reserved."  

# title: QAL ERP Documentation
# description: Official user documentation for QAL ERP — Accounting, Finance, and more.
# baseurl: "/qbs-docs"
# url: "https://quality-feeds-limited.github.io"

# remote_theme: just-the-docs/just-the-docs
# plugins:
#   - jekyll-remote-theme
#   - jekyll-seo-tag

# color_scheme: default

# aux_links:
#   "QAL ERP Login":
#     - "https://qbs-test.qfl.com.bd"
# aux_links_new_tab: true

# search_enabled: true

# footer_content: "Copyright &copy; 2026 QAL ERP. All rights reserved."

# back_to_top: true
# back_to_top_text: "Back to top"

# heading_anchors: true

# nav_sort: order

# callouts_level: quiet
# callouts:
#   highlight:
#     color: yellow
#   important:
#     title: Important
#     color: blue
#   new:
#     title: New
#     color: green
#   note:
#     title: Note
#     color: purple
#   warning:
#     title: Warning
#     color: red
